# Generated by Django 3.0.2 on 2020-04-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thecourt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
