# Generated by Django 3.0.2 on 2020-04-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thecourt', '0002_auto_20200401_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='players',
        ),
    ]
