# Generated by Django 3.0.2 on 2020-04-03 16:12

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('thecourt', '0003_auto_20200401_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thecourt.Players'),
        ),
        migrations.AlterField(
            model_name='players',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
